//UI
//ARTICLES
export const GET_NEWEST_ARTICLE = "GET_NEWEST_ARTICLE";
export const GET_MOST_VIEWED_ARTICLES = "GET_MOST_VIEWED_ARTICLES";
export const GET_ONE_ARTICLE = "GET_ONE_ARTICLE";
export const GET_SIMILAR_ARTICLES = "GET_SIMILAR_ARTICLES";
export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES";
export const GET_ALL_ARTICLES_BY_MOUNTAIN_NAME = "GET_ALL_ARTICLES_BY_MOUNTAIN_NAME";
export const GET_ARTICLE_BY_DISCRIPTION = "GET_ARTICLE_BY_DISCRIPTION";

//PHOTOS
export const GET_RANDOM_PHOTO = "GET_RANDOM_PHOTO";
export const GET_ALL_PHOTOS = "GET_ALL_PHOTOS";
export const GET_ONE_MOUNTAIN_PHOTOS = "GET_ONE_MOUNTAIN_PHOTOS";
export const GET_MOUNTAINS_NAME_LIST = "GET_MOUNTAINS_NAME_LIST";

//Mountains
export const GET_ALL_MOUNTAINS_NAME = "GET_ALL_MOUNTAINS_NAME";

//ADMIN
export const GET_ALL_ARTICLES_FOR_ADMIN = "GET_ALL_ARTICLES_FOR_ADMIN";
export const GET_ONE_ARTICLE_FOR_ADMIN = "GET_ONE_ARTICLE_FOR_ADMIN";
export const SAVE_ARTICLE = "SAVE_ARTICLE";
export const DELETE_ONE_ARTICLE = "DELETE_ONE_ARTICLE";
export const EDIT_ARTICLE = "EDIT_ARTICLE";

//Mountains
export const GET_ALL_MOUNTAINS_FOR_ADMIN = "GET_ALL_MOUNTAINS_FOR_ADMIN";
export const SAVE_MOUNTAIN = "SAVE_MOUNTAIN";
export const DELETE_MOUNTAIN = "DELETE_MOUNTAIN";
export const GET_COUNTRIES_AND_SYSTEM_FOR_CREATING_MOUNTAIN =
  "GET_COUNTRIES_AND_SYSTEM_FOR_CREATING_MOUNTAIN";
export const GET_ONE_MOUNTAIN_FOR_ADMIN = "GET_ONE_MOUNTAIN_FOR_ADMIN";
export const EDIT_MOUNTAIN = "EDIT_MOUNTAIN";

//Countries
export const GET_ALL_COUNTRIES_FOR_ADMIN = "GET_ALL_COUNTRIES_FOR_ADMIN";
export const REQUEST_COUNTRIES = "REQUEST_COUNTRIES";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const GET_ONE_COUNTRY_FOR_ADMIN = "GET_ONE_COUNTRY_FOR_ADMIN";
export const SAVE_COUNTRY = "SAVE_COUNTRY";
export const EDIT_COUNTRY = "EDIT_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";

//SYSTEMS
export const GET_ALL_SYSTEMS_FOR_ADMIN = "GET_ALL_SYSTEMS_FOR_ADMIN";
export const SAVE_SYSTEM = "SAVE_SYSTEM";
export const GET_ONE_SYSTEM_FOR_ADMIN = "GET_ONE_SYSTEM_FOR_ADMIN";
export const DELETE_SYSTEM = "DELETE_SYSTEM";
export const EDIT_SYSTEM = "EDIT_SYSTEM";
